name: Two-Way Server Ping

on:
  schedule:
    - cron: '0 */6 * * *' # Har 6 soatda ishlaydi
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Oracle Server
        run: curl -s http://213.35.119.223:8080 || true
